import type { NextPage } from "next";
import Head from "next/head";
import { GlobalStyle } from "../components-ui/GlobalStyle";
import styled from "styled-components";

const Home: NextPage = () => {
  return (
    <Wrapper>
      <GlobalStyle />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </Wrapper>
  );
};

const Wrapper = styled.div``;

export default Home;
